Major rewriting

diff --git a/plugins/gentoo/ekrnlmk b/plugins/gentoo/ekrnlmk
--- a/plugins/gentoo/ekrnlmk
+++ b/plugins/gentoo/ekrnlmk
@@ -1,103 +1,83 @@
-print -P "%B%F{cyan}$0%f - automated kernel builder%b"
-while [[ $1 ]]; do
-  case $1 in
-    --no-pause)
-      local _nopause=1
-      ;;
-    --no-clean)
-      local _noclean=1
-      ;;
-  esac
-  shift
-done
-pushd -q /usr/src/linux
-print "Current kernel  : $(uname -r)"
-local _ver="$(make kernelversion)"
-local _mod="$(awk -F"=" '$1 == "CONFIG_LOCALVERSION" { print substr($2, 2, length($2)-2); end; }' .config)"
+
+local _me="$0"
+local _ver
+local _mod
 local _rslt
-print "About to compile: ${_ver}${_mod}"
+local _nopause
+local _noclean
+local _noinst
+
+function _print_help() {
+  print "\nCompiles & install 'raw' kernel (no initramfs creation), including kernel modules (@module-rebuild)"
+  print "\nAvailable options:\n"
+  print -P "  %B--no-clean%b    Do not run 'make clean' prior to kernel compilation"
+  print -P "  %B--no-install%b  Do not install (only compile)"
+  print -P "  %B--no-pause%b    Do not confirm continuation after every stage"
+  print "                Note: Any stage error will still cause an abort."
+  print ""
+}
 
 function _contq() {
-  local _c
-  read -r -q "_c?Continue [yN]?"
-  print -P "%b"
-  if [[ $_c != "y" ]]; then
-    return 255
+  local __c
+  print -Pn "%B%F{yellow}"
+  read -r -q "__c?Continue [yN]?"
+  print -P "%f%b"
+  if [[ $__c != "y" ]]; then
+    return ${1:-255}
   fi
   return 0
 }
-
-if ! _contq; then
-  unfunction _contq
-  return
-fi
 
 function _stage() {
   local __args=()
   local __pre
   local __title
+  local __rslt
   while [[ $1 ]]; do
+    # The '/*=/' means substitute everything from start up to and including the equals '=' sign, with nothing
+    # In other words, deleting from start up to and including the first equals sign.
+    # This removes the need to count number of chars, which is kind of fragile.
     case "$1" in
       pre=*)
-        __pre="${1:4}"
+        __pre="${1/*=/}"
         ;;
       title=*)
-        __title="${1:6}"
+        __title="${1/*=/}"
         ;;
       *)
         __args+=( "$1" )
+        ;;
     esac
     shift
   done
-  if [[ -z %__title ]]; then
-    __title="${__args[@]}"
-  fi
-  local __rslt
-  print -P "\n%B%F{cyan}###%f $__title %F{green}${(l:50::=:)}%f%b\n"
+  print -P "\n%B%F{cyan}###%f ${__title:=${__args[*]}} %F{green}${(l:50::=:)}%f%b\n"
   if [[ $__pre ]]; then
     if ! $__pre; then
-      return 255
+      return $?
     fi
   fi
-  gsubex "$@"
+  echo gsubex "${__args[@]}"
   __rslt=$?
   if [[ $__rslt != 0 ]]; then
     print -P "%B%F{red}ERROR:${__rslt}%f - ekrnlmk aborted!%b\n"
     return $__rslt
   fi
+  print -P "\n%B%F{green}----------%f %F{cyan}$__title%f finished on %D{%Y-%m-%d %H:%M}"
   if [[ -z $_nopause ]]; then
-    print -P "\n%B%F{green}----------%f %F{cyan}$1 $2%f finished on %D{%Y-%m-%d %H:%M }"
     if ! _contq; then
       print -P "%B%F{yellow}ekrnlmk aborted by user.%f%b\n"
-      unfunction _contq
-      return 255
+      return 125  #ECANCELED
     fi
   fi
   return 0
 }
-
-if ! _stage make clean; then
-  unfunction _stage
-  return
-fi
-
-if ! _stage make; then
-  unfunction _stage
-  return
-fi
-
-if ! _stage make modules_install; then
-  unfunction _stage
-  return
-fi
 
 function _check_boot_writable() {
   local __tmp="$(gsubex mktemp -p /boot 2> /dev/null)"
   if [[ $? != 0 || -z $__tmp ]]; then
     print -P "%B%F{yellow}WARNING: /boot is not writable!%f"
     if ! _contq; then
-      unfunction _contq
-      return 255
+      return 13  # EACCESS
     fi
     print -P "%b"
   else
@@ -106,29 +86,75 @@ function _check_boot_writable() {
   return 0
 }
 
-_stage "pre=_check_boot_writable" make install
-_rslt="$?"
-unfunction _check_boot_writable
-if [[ $_rslt != 0 ]]; then
-  unfunction _stage
-  return
+trap 'unset _me _ver _mod _rslt _nopause _noclean _noinst; unfunction _print_help _contq _stage _check_boot_writable; popd -q; trap - EXIT' EXIT
+
+pushd -q /usr/src/linux
+if ! type gsubex > /dev/null; then
+  print -P "%B%F{red}ERROR:%f need '%F{yellow}gsubex%f' function/alias to be defined!%b"
+  return 3  # ESRCH
+elif i! [[ -f .config ]]; then
+  print -P "%B%F{red}ERROR:%f File '%F{yellow}.config%f' not found!%b"
+  return 2  # ENOENT
 fi
 
-if ! _stage grub-mkconfig -o /boot/grub/grub.cfg; then
-  unfunction _stage
-  return
+print -P "%B%F{cyan}${_me}%f - automated kernel builder & installer%b"
+while [[ $1 ]]; do
+  case $1 in
+    --help)
+      _print_help
+      return
+      ;;
+    --no-pause)
+      _nopause=1
+      ;;
+    --no-clean)
+      _noclean=1
+      ;;
+    --no-install)
+      _noinst=1
+      ;;
+  esac
+  shift
+done
+
+print ""
+print -P "Current kernel  : %B$(uname -r)%b"
+_ver="$(make kernelversion)"
+_mod="$(awk -F"=" '$1 == "CONFIG_LOCALVERSION" { print substr($2, 2, length($2)-2); end; }' .config)"
+print -P "About to compile: %B${_ver}${_mod}%b"
+if ! _contq 125; then
+  return $?
 fi
 
-if ! _stage emmodreb; then
-  unfunction _stage
-  return
+if ! _stage make clean; then
+  return $?
 fi
 
-print -P "\m%B%F{green}==========%f ekrnlmk Done %F{green}==========%f%b\n"
+if ! _stage make; then
+  return $?
+fi
 
-unfunction _stage
-unfunction _contq
+if [[ -z $_noinst ]]; then
 
-popd -q
+  if ! _stage make modules_install; then
+    return $?
+  fi
+
+  if ! _stage pre="_check_boot_writable" make install; then
+    return $?
+  fi
+
+  if ! _stage title="grub-mkconfig" grub-mkconfig -o /boot/grub/grub.cfg; then
+    return $?
+  fi
+
+  if ! _stage emmodreb; then
+    return $?
+  fi
+
+fi
+
+print -P "\n%B%F{green}==========%f $_me Done %F{green}==========%f%b\n"
+
 
 # vim: set ft=zsh:
